---
- name: "Role Foundation for all Nodes"
  hosts: all
  become: yes
  vars:
    env: dev

  roles:
    - common
    - cloudwatch_agent
    - security-hardening

- name: "Web Tier: Nginx Reverse Proxy"
  hosts: tag_Role_Web
  become: yes
  roles:
    - nginx
