---
services_to_disable:
  - name: autofs
    package: autofs
    condition: "{{ cis_services_disable_autofs }}"
    
  - name: avahi-daemon
    package: avahi
    condition: "{{ cis_services_disable_avahi }}"
    
  - name: cups
    package: cups
    condition: "{{ cis_services_disable_cups }}"
    
  - name: dhcpd
    package: dhcp-server
    condition: "{{ cis_services_disable_dhcpd }}"
    
  - name: slapd
    package: openldap-servers
    condition: "{{ cis_services_disable_slapd }}"
    
  - name: nfs-server
    package: nfs-utils
    condition: "{{ cis_services_disable_nfs }}"
    
  - name: rpcbind
    package: rpcbind
    condition: "{{ cis_services_disable_rpcbind }}"
    
  - name: named
    package: bind
    condition: "{{ cis_services_disable_named }}"
    
  - name: vsftpd
    package: vsftpd
    condition: "{{ cis_services_disable_vsftpd }}"
    
  - name: httpd
    package: httpd
    condition: "{{ cis_services_disable_httpd }}"
    
  - name: dovecot
    package: dovecot
    condition: "{{ cis_services_disable_dovecot }}"
    
  - name: smb
    package: samba
    condition: "{{ cis_services_disable_smb }}"
    
  - name: squid
    package: squid
    condition: "{{ cis_services_disable_squid }}"
    
  - name: snmpd
    package: net-snmp
    condition: "{{ cis_services_disable_snmpd }}"
    
  - name: rsyncd
    package: rsync-daemon
    condition: "{{ cis_services_disable_rsync }}"
    
  - name: ypbind
    package: ypbind
    condition: "{{ cis_services_disable_ypbind }}"
    
  - name: rsh
    package: rsh
    condition: "{{ cis_services_disable_rsh_client }}"
    
  - name: talk
    package: talk
    condition: "{{ cis_services_disable_talk_client }}"
    
  - name: telnet
    package: telnet
    condition: "{{ cis_services_disable_telnet_client }}"
