---
- name: Install CloudWatch Agent from official S3 URL
  yum:
    name: "https://s3.amazonaws.com/amazoncloudwatch-agent/amazon_linux/amd64/latest/amazon-cloudwatch-agent.rpm"
    state: present
    disable_gpg_check: yes # The AWS RPM is self-signed/Amazon-signed

- name: Deploy CloudWatch Agent configuration
  template:
    src: amazon-cloudwatch-agent.json.j2
    dest: /opt/aws/amazon-cloudwatch-agent/etc/amazon-cloudwatch-agent.json
    owner: root
    group: root
    mode: '0644'
  become: yes
  notify: Restart CloudWatch Agent

- name: Ensure CloudWatch Agent is started and enabled
  service:
    name: amazon-cloudwatch-agent
    state: started
    enabled: yes
  become: yes
