---
- name: restart rsyslog
  systemd:
    name: rsyslog
    state: restarted
  when: ansible_service_mgr == "systemd"

- name: restart journald
  systemd:
    name: systemd-journald
    state: restarted
  when: ansible_service_mgr == "systemd"
